<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ProfileOption;

class ProfileOptionsSeeder extends Seeder
{
    public function run(): void
    {
        // Complete snapshot of all profile options (as of September 25, 2025)
        $allOptions = [
            [
                'id' => 1,
                'category' => 'gender',
                'option_key' => 'weiblich',
                'option_value' => 'Weiblich',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2025-09-25 00:25:55',
                'updated_at' => '2025-09-25 00:25:55',
            ],
            [
                'id' => 2,
                'category' => 'gender',
                'option_key' => 'mannlich',
                'option_value' => 'Männlich',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2025-09-25 00:25:55',
                'updated_at' => '2025-09-25 00:25:55',
            ],
            [
                'id' => 3,
                'category' => 'body_type',
                'option_key' => 'latina',
                'option_value' => 'Latina',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2025-09-25 00:25:55',
                'updated_at' => '2025-09-25 00:25:55',
            ],
            [
                'id' => 4,
                'category' => 'body_type',
                'option_key' => 'sudlandisch',
                'option_value' => 'Südländisch',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2025-09-25 00:25:56',
                'updated_at' => '2025-09-25 00:25:56',
            ],
            [
                'id' => 5,
                'category' => 'body_type',
                'option_key' => 'karibisch',
                'option_value' => 'Karibisch',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2025-09-25 00:25:56',
                'updated_at' => '2025-09-25 00:25:56',
            ],
            [
                'id' => 6,
                'category' => 'body_type',
                'option_key' => 'westeuropaisch',
                'option_value' => 'Westeuropäisch',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 4,
                'created_at' => '2025-09-25 00:25:56',
                'updated_at' => '2025-09-25 00:25:56',
            ],
            [
                'id' => 7,
                'category' => 'body_type',
                'option_key' => 'osteuropaisch',
                'option_value' => 'Osteuropäisch',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 5,
                'created_at' => '2025-09-25 00:25:56',
                'updated_at' => '2025-09-25 00:25:56',
            ],
            [
                'id' => 8,
                'category' => 'origin',
                'option_key' => 'chile',
                'option_value' => 'Chile',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2025-09-25 00:25:56',
                'updated_at' => '2025-09-25 00:25:56',
            ],
            [
                'id' => 9,
                'category' => 'origin',
                'option_key' => 'spanien',
                'option_value' => 'Spanien',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2025-09-25 00:25:56',
                'updated_at' => '2025-09-25 00:25:56',
            ],
            [
                'id' => 10,
                'category' => 'origin',
                'option_key' => 'kolumbien',
                'option_value' => 'Kolumbien',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2025-09-25 00:25:56',
                'updated_at' => '2025-09-25 00:25:56',
            ],
            [
                'id' => 11,
                'category' => 'origin',
                'option_key' => 'italien',
                'option_value' => 'Italien',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 4,
                'created_at' => '2025-09-25 00:25:56',
                'updated_at' => '2025-09-25 00:25:56',
            ],
            [
                'id' => 12,
                'category' => 'origin',
                'option_key' => 'rumänien',
                'option_value' => 'Rumänien',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 5,
                'created_at' => '2025-09-25 00:25:57',
                'updated_at' => '2025-09-25 00:25:57',
            ],
            [
                'id' => 13,
                'category' => 'origin',
                'option_key' => 'karibik',
                'option_value' => 'Karibik',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 6,
                'created_at' => '2025-09-25 00:25:57',
                'updated_at' => '2025-09-25 00:25:57',
            ],
            [
                'id' => 14,
                'category' => 'origin',
                'option_key' => 'osteuropa',
                'option_value' => 'Osteuropa',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 7,
                'created_at' => '2025-09-25 00:25:57',
                'updated_at' => '2025-09-25 00:25:57',
            ],
            [
                'id' => 15,
                'category' => 'language',
                'option_key' => 'deutsch',
                'option_value' => 'Deutsch',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2025-09-25 00:25:57',
                'updated_at' => '2025-09-25 00:25:57',
            ],
            [
                'id' => 16,
                'category' => 'language',
                'option_key' => 'englisch',
                'option_value' => 'Englisch',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2025-09-25 00:25:57',
                'updated_at' => '2025-09-25 00:25:57',
            ],
            [
                'id' => 17,
                'category' => 'language',
                'option_key' => 'spanisch',
                'option_value' => 'Spanisch',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2025-09-25 00:25:57',
                'updated_at' => '2025-09-25 00:25:57',
            ],
            [
                'id' => 18,
                'category' => 'language',
                'option_key' => 'italienisch',
                'option_value' => 'Italienisch',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 4,
                'created_at' => '2025-09-25 00:25:57',
                'updated_at' => '2025-09-25 00:25:57',
            ],
            [
                'id' => 19,
                'category' => 'language',
                'option_key' => 'rumänisch',
                'option_value' => 'Rumänisch',
                'option_value_en' => null,
                'description' => null,
                'is_active' => 1,
                'sort_order' => 5,
                'created_at' => '2025-09-25 00:25:57',
                'updated_at' => '2025-09-25 00:25:57',
            ],
            // ... many more options would be here - truncated for brevity
            // In a real implementation, all 114 options would be included
        ];
        $allOptions = [
  0 => 
  array (
    'id' => 1,
    'category' => 'gender',
    'option_key' => 'weiblich',
    'option_value' => 'Weiblich',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:25:55',
    'updated_at' => '2025-09-25 00:25:55',
  ),
  1 => 
  array (
    'id' => 2,
    'category' => 'gender',
    'option_key' => 'mannlich',
    'option_value' => 'Männlich',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:25:55',
    'updated_at' => '2025-09-25 00:25:55',
  ),
  2 => 
  array (
    'id' => 3,
    'category' => 'body_type',
    'option_key' => 'latina',
    'option_value' => 'Latina',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:25:55',
    'updated_at' => '2025-09-25 00:25:55',
  ),
  3 => 
  array (
    'id' => 4,
    'category' => 'body_type',
    'option_key' => 'sudlandisch',
    'option_value' => 'Südländisch',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:25:56',
    'updated_at' => '2025-09-25 00:25:56',
  ),
  4 => 
  array (
    'id' => 5,
    'category' => 'body_type',
    'option_key' => 'karibisch',
    'option_value' => 'Karibisch',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:25:56',
    'updated_at' => '2025-09-25 00:25:56',
  ),
  5 => 
  array (
    'id' => 6,
    'category' => 'body_type',
    'option_key' => 'westeuropaisch',
    'option_value' => 'Westeuropäisch',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 4,
    'created_at' => '2025-09-25 00:25:56',
    'updated_at' => '2025-09-25 00:25:56',
  ),
  6 => 
  array (
    'id' => 7,
    'category' => 'body_type',
    'option_key' => 'osteuropaisch',
    'option_value' => 'Osteuropäisch',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 5,
    'created_at' => '2025-09-25 00:25:56',
    'updated_at' => '2025-09-25 00:25:56',
  ),
  7 => 
  array (
    'id' => 8,
    'category' => 'origin',
    'option_key' => 'chile',
    'option_value' => 'Chile',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:25:56',
    'updated_at' => '2025-09-25 00:25:56',
  ),
  8 => 
  array (
    'id' => 9,
    'category' => 'origin',
    'option_key' => 'spanien',
    'option_value' => 'Spanien',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:25:56',
    'updated_at' => '2025-09-25 00:25:56',
  ),
  9 => 
  array (
    'id' => 10,
    'category' => 'origin',
    'option_key' => 'kolumbien',
    'option_value' => 'Kolumbien',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:25:56',
    'updated_at' => '2025-09-25 00:25:56',
  ),
  10 => 
  array (
    'id' => 11,
    'category' => 'origin',
    'option_key' => 'italien',
    'option_value' => 'Italien',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 4,
    'created_at' => '2025-09-25 00:25:56',
    'updated_at' => '2025-09-25 00:25:56',
  ),
  11 => 
  array (
    'id' => 12,
    'category' => 'origin',
    'option_key' => 'rumänien',
    'option_value' => 'Rumänien',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 5,
    'created_at' => '2025-09-25 00:25:57',
    'updated_at' => '2025-09-25 00:25:57',
  ),
  12 => 
  array (
    'id' => 13,
    'category' => 'origin',
    'option_key' => 'karibik',
    'option_value' => 'Karibik',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 6,
    'created_at' => '2025-09-25 00:25:57',
    'updated_at' => '2025-09-25 00:25:57',
  ),
  13 => 
  array (
    'id' => 14,
    'category' => 'origin',
    'option_key' => 'osteuropa',
    'option_value' => 'Osteuropa',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 7,
    'created_at' => '2025-09-25 00:25:57',
    'updated_at' => '2025-09-25 00:25:57',
  ),
  14 => 
  array (
    'id' => 15,
    'category' => 'language',
    'option_key' => 'deutsch',
    'option_value' => 'Deutsch',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:25:57',
    'updated_at' => '2025-09-25 00:25:57',
  ),
  15 => 
  array (
    'id' => 16,
    'category' => 'language',
    'option_key' => 'englisch',
    'option_value' => 'Englisch',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:25:57',
    'updated_at' => '2025-09-25 00:25:57',
  ),
  16 => 
  array (
    'id' => 17,
    'category' => 'language',
    'option_key' => 'spanisch',
    'option_value' => 'Spanisch',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:25:57',
    'updated_at' => '2025-09-25 00:25:57',
  ),
  17 => 
  array (
    'id' => 18,
    'category' => 'language',
    'option_key' => 'italienisch',
    'option_value' => 'Italienisch',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 4,
    'created_at' => '2025-09-25 00:25:57',
    'updated_at' => '2025-09-25 00:25:57',
  ),
  18 => 
  array (
    'id' => 19,
    'category' => 'language',
    'option_key' => 'rumänisch',
    'option_value' => 'Rumänisch',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 5,
    'created_at' => '2025-09-25 00:25:57',
    'updated_at' => '2025-09-25 00:25:57',
  ),
  19 => 
  array (
    'id' => 20,
    'category' => 'intimate_area',
    'option_key' => 'total_rasiert',
    'option_value' => 'Total rasiert',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:25:57',
    'updated_at' => '2025-09-25 00:25:57',
  ),
  20 => 
  array (
    'id' => 21,
    'category' => 'intimate_area',
    'option_key' => 'teilrasiert',
    'option_value' => 'Teilrasiert',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:25:58',
    'updated_at' => '2025-09-25 00:25:58',
  ),
  21 => 
  array (
    'id' => 22,
    'category' => 'hair_color',
    'option_key' => 'brunett',
    'option_value' => 'Brünett',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:25:58',
    'updated_at' => '2025-09-25 00:25:58',
  ),
  22 => 
  array (
    'id' => 23,
    'category' => 'hair_color',
    'option_key' => 'schwarz',
    'option_value' => 'Schwarz',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:25:58',
    'updated_at' => '2025-09-25 00:25:58',
  ),
  23 => 
  array (
    'id' => 24,
    'category' => 'hair_color',
    'option_key' => 'dunkelbraun',
    'option_value' => 'Dunkelbraun',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:25:58',
    'updated_at' => '2025-09-25 00:25:58',
  ),
  24 => 
  array (
    'id' => 25,
    'category' => 'hair_color',
    'option_key' => 'dunkelblond',
    'option_value' => 'Dunkelblond',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 4,
    'created_at' => '2025-09-25 00:25:58',
    'updated_at' => '2025-09-25 00:25:58',
  ),
  25 => 
  array (
    'id' => 26,
    'category' => 'hair_color',
    'option_key' => 'blond',
    'option_value' => 'Blond',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 5,
    'created_at' => '2025-09-25 00:25:58',
    'updated_at' => '2025-09-25 00:25:58',
  ),
  26 => 
  array (
    'id' => 27,
    'category' => 'hair_color',
    'option_key' => 'wechselnd',
    'option_value' => 'Wechselnd',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 6,
    'created_at' => '2025-09-25 00:25:59',
    'updated_at' => '2025-09-25 00:25:59',
  ),
  27 => 
  array (
    'id' => 28,
    'category' => 'hair_length',
    'option_key' => 'ruckenlang',
    'option_value' => 'Rückenlang',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:25:59',
    'updated_at' => '2025-09-25 00:25:59',
  ),
  28 => 
  array (
    'id' => 29,
    'category' => 'hair_length',
    'option_key' => 'schulterlang',
    'option_value' => 'Schulterlang',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:25:59',
    'updated_at' => '2025-09-25 00:25:59',
  ),
  29 => 
  array (
    'id' => 30,
    'category' => 'hair_length',
    'option_key' => 'glatt',
    'option_value' => 'Glatt',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:25:59',
    'updated_at' => '2025-09-25 00:25:59',
  ),
  30 => 
  array (
    'id' => 31,
    'category' => 'hair_length',
    'option_key' => 'braids',
    'option_value' => 'Flechtzöpfchen',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 4,
    'created_at' => '2025-09-25 00:25:59',
    'updated_at' => '2025-09-25 00:25:59',
  ),
  31 => 
  array (
    'id' => 32,
    'category' => 'eye_color',
    'option_key' => 'braun',
    'option_value' => 'Braun',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:25:59',
    'updated_at' => '2025-09-25 00:25:59',
  ),
  32 => 
  array (
    'id' => 33,
    'category' => 'eye_color',
    'option_key' => 'grun',
    'option_value' => 'Grün',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:26:00',
    'updated_at' => '2025-09-25 00:26:00',
  ),
  33 => 
  array (
    'id' => 34,
    'category' => 'skin_type',
    'option_key' => 'mittel',
    'option_value' => 'Mittel',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:26:00',
    'updated_at' => '2025-09-25 00:26:00',
  ),
  34 => 
  array (
    'id' => 35,
    'category' => 'skin_type',
    'option_key' => 'hell',
    'option_value' => 'Hell',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:26:00',
    'updated_at' => '2025-09-25 00:26:00',
  ),
  35 => 
  array (
    'id' => 36,
    'category' => 'skin_type',
    'option_key' => 'braunlich',
    'option_value' => 'Bräunlich',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:26:00',
    'updated_at' => '2025-09-25 00:26:00',
  ),
  36 => 
  array (
    'id' => 37,
    'category' => 'body_jewelry',
    'option_key' => 'tattoos',
    'option_value' => 'Tattoos',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:26:00',
    'updated_at' => '2025-09-25 00:26:00',
  ),
  37 => 
  array (
    'id' => 38,
    'category' => 'body_jewelry',
    'option_key' => 'piercing',
    'option_value' => 'Piercing',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:26:01',
    'updated_at' => '2025-09-25 00:26:01',
  ),
  38 => 
  array (
    'id' => 39,
    'category' => 'body_jewelry',
    'option_key' => 'intim_piercing',
    'option_value' => 'Intim-Piercing',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:26:01',
    'updated_at' => '2025-09-25 00:26:01',
  ),
  39 => 
  array (
    'id' => 40,
    'category' => 'body_jewelry',
    'option_key' => 'brustwarzen_piercing',
    'option_value' => 'Brustwarzen-Piercing',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 4,
    'created_at' => '2025-09-25 00:26:01',
    'updated_at' => '2025-09-25 00:26:01',
  ),
  40 => 
  array (
    'id' => 41,
    'category' => 'body_jewelry',
    'option_key' => 'kein_schmuck',
    'option_value' => 'Kein Körperschmuck',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 5,
    'created_at' => '2025-09-25 00:26:01',
    'updated_at' => '2025-09-25 00:26:01',
  ),
  41 => 
  array (
    'id' => 42,
    'category' => 'other',
    'option_key' => 'nichtraucher',
    'option_value' => 'Nichtraucher',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:26:01',
    'updated_at' => '2025-09-25 00:26:01',
  ),
  42 => 
  array (
    'id' => 43,
    'category' => 'intercourse',
    'option_key' => 'gv',
    'option_value' => 'GV',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:26:02',
    'updated_at' => '2025-09-25 00:26:02',
  ),
  43 => 
  array (
    'id' => 44,
    'category' => 'intercourse',
    'option_key' => 'av',
    'option_value' => 'AV',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:26:02',
    'updated_at' => '2025-09-25 00:26:02',
  ),
  44 => 
  array (
    'id' => 45,
    'category' => 'intercourse',
    'option_key' => 'franz',
    'option_value' => 'Franz.',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:26:02',
    'updated_at' => '2025-09-25 00:26:02',
  ),
  45 => 
  array (
    'id' => 46,
    'category' => 'intercourse',
    'option_key' => 'franz_bei_ihr',
    'option_value' => 'Franz. bei Ihr',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 4,
    'created_at' => '2025-09-25 00:26:02',
    'updated_at' => '2025-09-25 00:26:02',
  ),
  46 => 
  array (
    'id' => 47,
    'category' => 'intercourse',
    'option_key' => 'franz_beidseitig',
    'option_value' => 'Franz. beidseitig',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 5,
    'created_at' => '2025-09-25 00:26:02',
    'updated_at' => '2025-09-25 00:26:02',
  ),
  47 => 
  array (
    'id' => 48,
    'category' => 'intercourse',
    'option_key' => 'deep_throat',
    'option_value' => 'D**p Thr**t',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 6,
    'created_at' => '2025-09-25 00:26:02',
    'updated_at' => '2025-09-25 00:26:02',
  ),
  48 => 
  array (
    'id' => 49,
    'category' => 'intercourse',
    'option_key' => 'span_bv',
    'option_value' => 'Span. / BV',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 7,
    'created_at' => '2025-09-25 00:26:02',
    'updated_at' => '2025-09-25 00:26:02',
  ),
  49 => 
  array (
    'id' => 50,
    'category' => 'intercourse',
    'option_key' => 'gf6',
    'option_value' => 'GF6',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 8,
    'created_at' => '2025-09-25 00:26:02',
    'updated_at' => '2025-09-25 00:26:02',
  ),
  50 => 
  array (
    'id' => 51,
    'category' => 'intercourse',
    'option_key' => 'kein_gv',
    'option_value' => 'KEIN GV',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 9,
    'created_at' => '2025-09-25 00:26:02',
    'updated_at' => '2025-09-25 00:26:02',
  ),
  51 => 
  array (
    'id' => 52,
    'category' => 'services_for',
    'option_key' => 'herren',
    'option_value' => 'Herren',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:26:03',
    'updated_at' => '2025-09-25 00:26:03',
  ),
  52 => 
  array (
    'id' => 53,
    'category' => 'service',
    'option_key' => 'schmusen_kuscheln',
    'option_value' => 'Schmusen, Kuscheln',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:26:03',
    'updated_at' => '2025-09-25 00:26:03',
  ),
  53 => 
  array (
    'id' => 54,
    'category' => 'service',
    'option_key' => 'korperkusse',
    'option_value' => 'Körperküsse',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:26:03',
    'updated_at' => '2025-09-25 00:26:03',
  ),
  54 => 
  array (
    'id' => 55,
    'category' => 'service',
    'option_key' => 'zk',
    'option_value' => 'ZK',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:26:03',
    'updated_at' => '2025-09-25 00:26:03',
  ),
  55 => 
  array (
    'id' => 56,
    'category' => 'service',
    'option_key' => 'ds_aktiv',
    'option_value' => 'DS aktiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 4,
    'created_at' => '2025-09-25 00:26:03',
    'updated_at' => '2025-09-25 00:26:03',
  ),
  56 => 
  array (
    'id' => 57,
    'category' => 'service',
    'option_key' => 'ds_passiv',
    'option_value' => 'DS passiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 5,
    'created_at' => '2025-09-25 00:26:03',
    'updated_at' => '2025-09-25 00:26:03',
  ),
  57 => 
  array (
    'id' => 58,
    'category' => 'service',
    'option_key' => 'za_passiv',
    'option_value' => 'ZA passiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 6,
    'created_at' => '2025-09-25 00:26:03',
    'updated_at' => '2025-09-25 00:26:03',
  ),
  58 => 
  array (
    'id' => 59,
    'category' => 'service',
    'option_key' => 'fa_analmassagen_aktiv',
    'option_value' => 'FA / An*l-Massagen aktiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 7,
    'created_at' => '2025-09-25 00:26:03',
    'updated_at' => '2025-09-25 00:26:03',
  ),
  59 => 
  array (
    'id' => 60,
    'category' => 'service',
    'option_key' => 'fa_analmassagen_passiv',
    'option_value' => 'FA / An*l-Massagen passiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 8,
    'created_at' => '2025-09-25 00:26:04',
    'updated_at' => '2025-09-25 00:26:04',
  ),
  60 => 
  array (
    'id' => 61,
    'category' => 'service',
    'option_key' => 'gb_passiv',
    'option_value' => 'GB passiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 9,
    'created_at' => '2025-09-25 00:26:04',
    'updated_at' => '2025-09-25 00:26:04',
  ),
  61 => 
  array (
    'id' => 62,
    'category' => 'service',
    'option_key' => 'kb_passiv',
    'option_value' => 'KB passiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 10,
    'created_at' => '2025-09-25 00:26:04',
    'updated_at' => '2025-09-25 00:26:04',
  ),
  62 => 
  array (
    'id' => 63,
    'category' => 'service',
    'option_key' => 'fingerspiele_aktiv',
    'option_value' => 'Fingerspiele aktiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 11,
    'created_at' => '2025-09-25 00:26:04',
    'updated_at' => '2025-09-25 00:26:04',
  ),
  63 => 
  array (
    'id' => 64,
    'category' => 'service',
    'option_key' => 'fingerspiele_passiv',
    'option_value' => 'Fingerspiele passiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 12,
    'created_at' => '2025-09-25 00:26:04',
    'updated_at' => '2025-09-25 00:26:04',
  ),
  64 => 
  array (
    'id' => 65,
    'category' => 'service',
    'option_key' => 'el',
    'option_value' => 'EL',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 13,
    'created_at' => '2025-09-25 00:26:04',
    'updated_at' => '2025-09-25 00:26:04',
  ),
  65 => 
  array (
    'id' => 66,
    'category' => 'service',
    'option_key' => 'mast',
    'option_value' => 'Mast.',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 14,
    'created_at' => '2025-09-25 00:26:05',
    'updated_at' => '2025-09-25 00:26:05',
  ),
  66 => 
  array (
    'id' => 67,
    'category' => 'service',
    'option_key' => 'av_bei_ihm',
    'option_value' => 'AV bei Ihm',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 15,
    'created_at' => '2025-09-25 00:26:05',
    'updated_at' => '2025-09-25 00:26:05',
  ),
  67 => 
  array (
    'id' => 68,
    'category' => 'service',
    'option_key' => 'extra_langes_vorspiel',
    'option_value' => 'Extra langes Vorspiel',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 16,
    'created_at' => '2025-09-25 00:26:05',
    'updated_at' => '2025-09-25 00:26:05',
  ),
  68 => 
  array (
    'id' => 69,
    'category' => 'service',
    'option_key' => 'gekonntes_striptease',
    'option_value' => 'Gekonntes Striptease',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 17,
    'created_at' => '2025-09-25 00:26:05',
    'updated_at' => '2025-09-25 00:26:05',
  ),
  69 => 
  array (
    'id' => 70,
    'category' => 'service',
    'option_key' => 'badeservice',
    'option_value' => 'Badeservice',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 18,
    'created_at' => '2025-09-25 00:26:05',
    'updated_at' => '2025-09-25 00:26:05',
  ),
  70 => 
  array (
    'id' => 71,
    'category' => 'service',
    'option_key' => 'duschservice',
    'option_value' => 'Duschservice',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 19,
    'created_at' => '2025-09-25 00:26:05',
    'updated_at' => '2025-09-25 00:26:05',
  ),
  71 => 
  array (
    'id' => 72,
    'category' => 'service',
    'option_key' => 'fuß_schuh_erotik',
    'option_value' => 'Fuß- / Schuherotik',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 20,
    'created_at' => '2025-09-25 00:26:05',
    'updated_at' => '2025-09-25 00:26:05',
  ),
  72 => 
  array (
    'id' => 73,
    'category' => 'service',
    'option_key' => 'intimrasur',
    'option_value' => 'Intimrasur',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 21,
    'created_at' => '2025-09-25 00:26:06',
    'updated_at' => '2025-09-25 00:26:06',
  ),
  73 => 
  array (
    'id' => 74,
    'category' => 'service',
    'option_key' => 'nylonerotik',
    'option_value' => 'Nylonerotik',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 22,
    'created_at' => '2025-09-25 00:26:06',
    'updated_at' => '2025-09-25 00:26:06',
  ),
  74 => 
  array (
    'id' => 75,
    'category' => 'service',
    'option_key' => 'ls_duo',
    'option_value' => 'LS / Duo',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 23,
    'created_at' => '2025-09-25 00:26:06',
    'updated_at' => '2025-09-25 00:26:06',
  ),
  75 => 
  array (
    'id' => 76,
    'category' => 'service',
    'option_key' => 'verbalerotik',
    'option_value' => 'Verbalerotik',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 24,
    'created_at' => '2025-09-25 00:26:06',
    'updated_at' => '2025-09-25 00:26:06',
  ),
  76 => 
  array (
    'id' => 77,
    'category' => 'meeting',
    'option_key' => 'mit_termin',
    'option_value' => 'Mit Termin',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:26:06',
    'updated_at' => '2025-09-25 00:26:06',
  ),
  77 => 
  array (
    'id' => 78,
    'category' => 'meeting',
    'option_key' => 'ohne_termin',
    'option_value' => 'Ohne Termin',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:26:06',
    'updated_at' => '2025-09-25 00:26:06',
  ),
  78 => 
  array (
    'id' => 79,
    'category' => 'massage',
    'option_key' => 'erot_massagen',
    'option_value' => 'Erot. Massagen',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:26:06',
    'updated_at' => '2025-09-25 00:26:06',
  ),
  79 => 
  array (
    'id' => 80,
    'category' => 'massage',
    'option_key' => 'he',
    'option_value' => 'HE',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:26:06',
    'updated_at' => '2025-09-25 00:26:06',
  ),
  80 => 
  array (
    'id' => 81,
    'category' => 'massage',
    'option_key' => 'body_to_body_massage',
    'option_value' => 'Body-to-Body-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:26:06',
    'updated_at' => '2025-09-25 00:26:06',
  ),
  81 => 
  array (
    'id' => 82,
    'category' => 'massage',
    'option_key' => 'tantra_massage',
    'option_value' => 'Tantra-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 4,
    'created_at' => '2025-09-25 00:26:07',
    'updated_at' => '2025-09-25 00:26:07',
  ),
  82 => 
  array (
    'id' => 83,
    'category' => 'massage',
    'option_key' => 'ganzkorper_massage',
    'option_value' => 'Ganzkörper-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 5,
    'created_at' => '2025-09-25 00:26:07',
    'updated_at' => '2025-09-25 00:26:07',
  ),
  83 => 
  array (
    'id' => 84,
    'category' => 'massage',
    'option_key' => 'intim_massagen',
    'option_value' => 'Intim-Massagen',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 6,
    'created_at' => '2025-09-25 00:26:07',
    'updated_at' => '2025-09-25 00:26:07',
  ),
  84 => 
  array (
    'id' => 85,
    'category' => 'massage',
    'option_key' => 'ol_massage',
    'option_value' => 'Öl-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 7,
    'created_at' => '2025-09-25 00:26:07',
    'updated_at' => '2025-09-25 00:26:07',
  ),
  85 => 
  array (
    'id' => 86,
    'category' => 'massage',
    'option_key' => 'synchron_massage',
    'option_value' => 'Synchron-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 8,
    'created_at' => '2025-09-25 00:26:07',
    'updated_at' => '2025-09-25 00:26:07',
  ),
  86 => 
  array (
    'id' => 87,
    'category' => 'massage',
    'option_key' => 'duo_massage',
    'option_value' => 'Duo-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 9,
    'created_at' => '2025-09-25 00:26:07',
    'updated_at' => '2025-09-25 00:26:07',
  ),
  87 => 
  array (
    'id' => 88,
    'category' => 'massage',
    'option_key' => 'nuru_massage',
    'option_value' => 'Nuru-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 10,
    'created_at' => '2025-09-25 00:26:07',
    'updated_at' => '2025-09-25 00:26:07',
  ),
  88 => 
  array (
    'id' => 89,
    'category' => 'massage',
    'option_key' => 'prostata_massage',
    'option_value' => 'Pr*stata-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 11,
    'created_at' => '2025-09-25 00:26:07',
    'updated_at' => '2025-09-25 00:26:07',
  ),
  89 => 
  array (
    'id' => 90,
    'category' => 'massage',
    'option_key' => 'po_massage',
    'option_value' => 'Po-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 12,
    'created_at' => '2025-09-25 00:26:08',
    'updated_at' => '2025-09-25 00:26:08',
  ),
  90 => 
  array (
    'id' => 91,
    'category' => 'massage',
    'option_key' => 'lingam_massage',
    'option_value' => 'Lingam-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 13,
    'created_at' => '2025-09-25 00:26:08',
    'updated_at' => '2025-09-25 00:26:08',
  ),
  91 => 
  array (
    'id' => 92,
    'category' => 'massage',
    'option_key' => 'spanische_massage',
    'option_value' => 'Spanische-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 14,
    'created_at' => '2025-09-25 00:26:08',
    'updated_at' => '2025-09-25 00:26:08',
  ),
  92 => 
  array (
    'id' => 93,
    'category' => 'massage',
    'option_key' => 'pärchen_massage',
    'option_value' => 'Pärchen-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 15,
    'created_at' => '2025-09-25 00:26:08',
    'updated_at' => '2025-09-25 00:26:08',
  ),
  93 => 
  array (
    'id' => 94,
    'category' => 'massage',
    'option_key' => 'thai_massage',
    'option_value' => 'Thai-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 16,
    'created_at' => '2025-09-25 00:26:08',
    'updated_at' => '2025-09-25 00:26:08',
  ),
  94 => 
  array (
    'id' => 95,
    'category' => 'massage',
    'option_key' => 'vierhand_massage',
    'option_value' => 'Vierhand-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 17,
    'created_at' => '2025-09-25 00:26:08',
    'updated_at' => '2025-09-25 00:26:08',
  ),
  95 => 
  array (
    'id' => 96,
    'category' => 'massage',
    'option_key' => 'dominante_massage',
    'option_value' => 'Dominante Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 18,
    'created_at' => '2025-09-25 00:26:08',
    'updated_at' => '2025-09-25 00:26:08',
  ),
  96 => 
  array (
    'id' => 97,
    'category' => 'massage',
    'option_key' => 'hot_stone_massage',
    'option_value' => 'Hot Stone Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 19,
    'created_at' => '2025-09-25 00:26:08',
    'updated_at' => '2025-09-25 00:26:08',
  ),
  97 => 
  array (
    'id' => 98,
    'category' => 'massage',
    'option_key' => 'bizarr_massage',
    'option_value' => 'Bizarr-Massage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 20,
    'created_at' => '2025-09-25 00:26:08',
    'updated_at' => '2025-09-25 00:26:08',
  ),
  98 => 
  array (
    'id' => 99,
    'category' => 'massage',
    'option_key' => 'paarmassage',
    'option_value' => 'Paarmassage',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 21,
    'created_at' => '2025-09-25 00:26:09',
    'updated_at' => '2025-09-25 00:26:09',
  ),
  99 => 
  array (
    'id' => 100,
    'category' => 'massage',
    'option_key' => 'zartliche_verfuhrung',
    'option_value' => 'Zärtliche Verführung',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 22,
    'created_at' => '2025-09-25 00:26:09',
    'updated_at' => '2025-09-25 00:26:09',
  ),
  100 => 
  array (
    'id' => 101,
    'category' => 'fetish',
    'option_key' => 'fetisch_softbizarr',
    'option_value' => 'Fetisch / Softbizarr',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2025-09-25 00:26:09',
    'updated_at' => '2025-09-25 00:26:09',
  ),
  101 => 
  array (
    'id' => 102,
    'category' => 'fetish',
    'option_key' => 'ns_aktiv',
    'option_value' => 'NS aktiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2025-09-25 00:26:09',
    'updated_at' => '2025-09-25 00:26:09',
  ),
  102 => 
  array (
    'id' => 103,
    'category' => 'fetish',
    'option_key' => 'ns_passiv',
    'option_value' => 'NS passiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 3,
    'created_at' => '2025-09-25 00:26:09',
    'updated_at' => '2025-09-25 00:26:09',
  ),
  103 => 
  array (
    'id' => 104,
    'category' => 'fetish',
    'option_key' => 'bru_tw_spiele_aktiv',
    'option_value' => 'Bru*tw.-Spiele aktiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 4,
    'created_at' => '2025-09-25 00:26:09',
    'updated_at' => '2025-09-25 00:26:09',
  ),
  104 => 
  array (
    'id' => 105,
    'category' => 'fetish',
    'option_key' => 'bru_tw_spiele_passiv',
    'option_value' => 'Bru*tw.-Spiele passiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 5,
    'created_at' => '2025-09-25 00:26:09',
    'updated_at' => '2025-09-25 00:26:09',
  ),
  105 => 
  array (
    'id' => 106,
    'category' => 'fetish',
    'option_key' => 'fess_spielchen_aktiv',
    'option_value' => 'Fess.-Spielchen aktiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 6,
    'created_at' => '2025-09-25 00:26:09',
    'updated_at' => '2025-09-25 00:26:09',
  ),
  106 => 
  array (
    'id' => 107,
    'category' => 'fetish',
    'option_key' => 'fess_spielchen_passiv',
    'option_value' => 'Fess.-Spielchen passiv',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 7,
    'created_at' => '2025-09-25 00:26:10',
    'updated_at' => '2025-09-25 00:26:10',
  ),
  107 => 
  array (
    'id' => 108,
    'category' => 'fetish',
    'option_key' => 'dom_biz_spielchen',
    'option_value' => 'Dom. Biz.-Spielchen',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 8,
    'created_at' => '2025-09-25 00:26:10',
    'updated_at' => '2025-09-25 00:26:10',
  ),
  108 => 
  array (
    'id' => 109,
    'category' => 'fetish',
    'option_key' => 'fetisch_spielchen',
    'option_value' => 'Fetisch-Spielchen',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 9,
    'created_at' => '2025-09-25 00:26:10',
    'updated_at' => '2025-09-25 00:26:10',
  ),
  109 => 
  array (
    'id' => 110,
    'category' => 'fetish',
    'option_key' => 'lack_und_leder',
    'option_value' => 'Lack u. Leder',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 10,
    'created_at' => '2025-09-25 00:26:10',
    'updated_at' => '2025-09-25 00:26:10',
  ),
  110 => 
  array (
    'id' => 111,
    'category' => 'fetish',
    'option_key' => 'latex',
    'option_value' => 'Latex',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 11,
    'created_at' => '2025-09-25 00:26:10',
    'updated_at' => '2025-09-25 00:26:10',
  ),
  111 => 
  array (
    'id' => 112,
    'category' => 'fetish',
    'option_key' => 'ws',
    'option_value' => 'WS',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 12,
    'created_at' => '2025-09-25 00:26:10',
    'updated_at' => '2025-09-25 00:26:10',
  ),
  112 => 
  array (
    'id' => 113,
    'category' => 'fetish',
    'option_key' => 'fs',
    'option_value' => 'FS',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 13,
    'created_at' => '2025-09-25 00:26:10',
    'updated_at' => '2025-09-25 00:26:10',
  ),
  113 => 
  array (
    'id' => 114,
    'category' => 'fetish',
    'option_key' => 'leichte_erz',
    'option_value' => 'Leichte Erz.',
    'option_value_en' => NULL,
    'description' => NULL,
    'is_active' => 1,
    'sort_order' => 14,
    'created_at' => '2025-09-25 00:26:10',
    'updated_at' => '2025-09-25 00:26:10',
  ),
];

        foreach ($allOptions as $optionData) {
            ProfileOption::updateOrCreate(
                ['id' => $optionData['id']],
                $optionData
            );
        }
    }
}
