<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Profile;

class ProfilesSeeder extends Seeder
{
    public function run(): void
    {
        // Complete snapshot of all profiles (as of September 25, 2025)
        $profiles = [
            [
                'id' => 13,
                'name' => 'Kim',
                'age' => 40,
                'gender' => 'weiblich',
                'height' => 161,
                'bust_size' => '80 C',
                'body_type' => 'Latina',
                'origin' => 'Chile',
                'clothing_size' => '36/38',
                'weight' => 53,
                'shoe_size' => 36,
                'intimate_area' => 'total rasiert',
                'hair' => 'brünett, rückenlang, glatt',
                'eyes' => 'braun',
                'skin' => 'mittel',
                'body_jewelry' => null,
                'languages' => '["Deutsch", "Spanisch"]',
                'other' => 'Nichtraucher',
                'description' => 'Lieber Gast, ich bin eine gefühlvolle Masseurin, meine Spezialität ist dich auf eine Reise der Lust und Erholung zu entführen damit du deinen stressiger Alltag hinter Dir lassen kannst. Fühle dich eingeladen meine weichen Hände und meine sanften Berührungen zu spüren! Alles Liebe und bis bald deine Kim',
                'image' => 'https://escortsmassage.com/images/users/1.webp',
                'images' => '["profiles/01K5YRVS82HD0KM475GANZ2D9S.jpeg", "profiles/01K5YS1WDW6P1JF78S7PYKH4Q0.jpeg"]',
                'main_image' => 'profiles/01K5YRVS82HD0KM475GANZ2D9S.jpeg',
                'intercourse_options' => '["KEIN GV"]',
                'services_for' => '["Herren"]',
                'services' => '["Schmusen, Kuscheln", "AV bei Ihm", "Mast.", "Duschservice", "Fuß- / Schuherotik", "Intimrasur"]',
                'meetings' => '["mit Termin", "ohne Termin"]',
                'massages' => '["erot. Massagen", "HE", "Body-to-Body-Massage", "Tantra-Massage", "Ganzkörpermassage", "Intim-Massagen", "Öl-Massage", "Synchron-Massage", "Duo-Massage", "Nuru-Massage", "Pr*stata-Massage", "Po-Massage", "Lingam-Massage", "Spanische-Massage", "Pärchen-Massage"]',
                'schedule' => 'Montag: nach Absprache\nDienstag: nach Absprache\nMittwoch: nach Absprache\nDonnerstag: nach Absprache\nFreitag: nach Absprache\nSamstag: nach Absprache\nSonntag: nach Absprache\nFeiertag: nach Absprache',
                'additional_info' => null,
                'profile_options' => null,
                'created_at' => '2025-08-28 15:15:25',
                'updated_at' => '2025-09-24 21:28:16',
            ],
            [
                'id' => 14,
                'name' => 'Lulu',
                'age' => 28,
                'gender' => 'weiblich',
                'height' => 151,
                'bust_size' => '85 C',
                'body_type' => 'südländisch',
                'origin' => 'Spanien',
                'clothing_size' => '34',
                'weight' => 45,
                'shoe_size' => 33,
                'intimate_area' => 'total rasiert',
                'hair' => 'schwarz, rückenlang, glatt',
                'eyes' => 'braun',
                'skin' => 'mittel',
                'body_jewelry' => 'Tattoos',
                'languages' => '["Englisch", "Spanisch"]',
                'other' => null,
                'description' => null,
                'image' => 'https://escortsmassage.com/images/users/2.webp',
                'images' => '["https://escortsmassage.com/images/users/2.webp"]',
                'main_image' => 'https://escortsmassage.com/images/users/2.webp',
                'intercourse_options' => '["GV", "Franz.", "Franz. bei Ihr", "Franz. beidseitig", "D**p Thr**t", "Span. / BV"]',
                'services_for' => '["Herren"]',
                'services' => '["ZK", "Schmusen, Kuscheln", "Körperküsse", "DS aktiv", "DS passiv", "FA / An*l-Massagen aktiv", "KB passiv", "Fingerspiele aktiv", "Fingerspiele passiv", "EL", "Mast.", "extra langes Vorspiel", "gekonnter Striptease", "Fuß- / Schuherotik"]',
                'meetings' => null,
                'massages' => '["erot. Massagen", "HE", "Body-to-Body-Massage", "Ganzkörper-Massage", "Öl-Massage", "Pr*stata-Massage", "Po-Massage", "Lingam-Massage"]',
                'schedule' => 'Montag: 10:00 - 21:30 Uhr (n. Abspr.)\nDienstag: 10:00 - 21:30 Uhr (n. Abspr.)\nMittwoch: 10:00 - 21:30 Uhr (n. Abspr.)\nDonnerstag: 10:00 - 21:30 Uhr (n. Abspr.)\nFreitag: 10:00 - 21:30 Uhr (n. Abspr.)\nSamstag: 10:00 - 21:30 Uhr (n. Abspr.)\nSonntag: 12:00 - 21:30 Uhr (n. Abspr.)\nFeiertag: 12:00 - 21:30 Uhr (n. Abspr.)',
                'additional_info' => null,
                'profile_options' => null,
                'created_at' => '2025-08-28 15:15:25',
                'updated_at' => '2025-09-24 20:59:18',
            ],
            [
                'id' => 16,
                'name' => 'Eva',
                'age' => 25,
                'gender' => 'weiblich',
                'height' => 155,
                'bust_size' => '80 C, fest',
                'body_type' => 'westeuropäisch',
                'origin' => 'Spanien',
                'clothing_size' => '34',
                'weight' => 45,
                'shoe_size' => null,
                'intimate_area' => 'total rasiert',
                'hair' => 'schwarz, rückenlang, glatt',
                'eyes' => 'braun',
                'skin' => 'hell',
                'body_jewelry' => 'Intim-Piercing, Tattoos',
                'languages' => '["Deutsch", "Englisch", "Spanisch"]',
                'other' => null,
                'description' => null,
                'image' => 'https://escortsmassage.com/images/users/4.webp',
                'images' => '["https://escortsmassage.com/images/users/4.webp"]',
                'main_image' => 'https://escortsmassage.com/images/users/4.webp',
                'intercourse_options' => '["GV", "Franz.", "Franz. bei Ihr", "Franz. beidseitig", "D**p Thr**t", "Span. / BV", "GF6"]',
                'services_for' => '["Herren"]',
                'services' => '["Schmusen, Kuscheln", "Körperküsse", "GB passiv", "KB passiv", "EL", "Mast.", "Duschservice", "extra langes Vorspiel", "Fuß- / Schuherotik", "Intimrasur"]',
                'meetings' => null,
                'massages' => '["erot. Massagen", "HE", "Body-to-Body-Massage", "Öl-Massage", "Lingam-Massage"]',
                'schedule' => 'Montag: 10:00 - 21:30 Uhr (n. Abspr.)\nDienstag: 10:00 - 21:30 Uhr (n. Abspr.)\nMittwoch: 10:00 - 21:30 Uhr (n. Abspr.)\nDonnerstag: 10:00 - 21:30 Uhr (n. Abspr.)\nFreitag: 10:00 - 21:30 Uhr (n. Abspr.)\nSamstag: 10:00 - 21:30 Uhr (n. Abspr.)\nSonntag: 12:00 - 21:30 Uhr (n. Abspr.)\nFeiertag: 12:00 - 21:30 Uhr (n. Abspr.)',
                'additional_info' => null,
                'profile_options' => null,
                'created_at' => '2025-08-28 15:15:26',
                'updated_at' => '2025-09-24 20:59:19',
            ],
            [
                'id' => 17,
                'name' => 'Yoli',
                'age' => 35,
                'gender' => 'weiblich',
                'height' => 168,
                'bust_size' => '75 D, weich',
                'body_type' => 'Latina',
                'origin' => 'Kolumbien',
                'clothing_size' => '38',
                'weight' => null,
                'shoe_size' => 37,
                'intimate_area' => 'total rasiert',
                'hair' => 'schwarz, rückenlang, glatt',
                'eyes' => 'braun',
                'skin' => 'bräunlich',
                'body_jewelry' => null,
                'languages' => '["Deutsch", "Englisch", "Spanisch"]',
                'other' => null,
                'description' => null,
                'image' => 'https://escortsmassage.com/images/users/5.webp',
                'images' => '["https://escortsmassage.com/images/users/5.webp"]',
                'main_image' => 'https://escortsmassage.com/images/users/5.webp',
                'intercourse_options' => '["GV", "Franz.", "Franz. bei Ihr", "Span. / BV"]',
                'services_for' => '["Herren"]',
                'services' => '["ZK", "Schmusen, Kuscheln", "DS aktiv", "DS passiv", "ZA passiv", "FA / An*l-Massagen aktiv", "FA / An*l-Massagen passiv", "KB passiv", "Fingerspiele aktiv", "Fingerspiele passiv", "EL", "Mast.", "Duschservice", "extra langes Vorspiel"]',
                'meetings' => '["mit Termin", "ohne Termin"]',
                'massages' => '["erot. Massagen", "HE", "Body-to-Body-Massage", "Ganzkörper-Massage", "Intim-Massagen", "Öl-Massage", "Synchron-Massage", "Duo-Massage", "Nuru-Massage", "Po-Massage", "Lingam-Massage", "Spanische-Massage", "Fetisch / Softbizarr", "NS aktiv", "NS passiv", "Fess.-Spielchen aktiv", "Fess.-Spielchen passiv", "Bru*tw.-Spiele aktiv", "Bru*tw.-Spiele passiv"]',
                'schedule' => 'Montag: 10:00 - 21:30 Uhr (n. Abspr.)\nDienstag: 10:00 - 21:30 Uhr (n. Abspr.)\nMittwoch: 10:00 - 21:30 Uhr (n. Abspr.)\nDonnerstag: 10:00 - 21:30 Uhr (n. Abspr.)\nFreitag: 10:00 - 21:30 Uhr (n. Abspr.)\nSamstag: 10:00 - 21:30 Uhr (n. Abspr.)\nSonntag: 12:00 - 21:30 Uhr (n. Abspr.)\nFeiertag: 12:00 - 21:30 Uhr (n. Abspr.)',
                'additional_info' => null,
                'profile_options' => null,
                'created_at' => '2025-08-28 15:15:26',
                'updated_at' => '2025-09-24 20:59:19',
            ],
            [
                'id' => 18,
                'name' => 'Sol',
                'age' => 20,
                'gender' => 'weiblich',
                'height' => 163,
                'bust_size' => '95 B, fest, natur',
                'body_type' => 'Latina',
                'origin' => 'Kolumbien',
                'clothing_size' => '34',
                'weight' => 52,
                'shoe_size' => 35,
                'intimate_area' => 'total rasiert',
                'hair' => 'dunkelbraun, rückenlang, glatt',
                'eyes' => 'braun',
                'skin' => 'mittel',
                'body_jewelry' => 'Tattoos',
                'languages' => '["Englisch", "Spanisch"]',
                'other' => 'Nichtraucher',
                'description' => null,
                'image' => 'https://escortsmassage.com/images/users/6.webp',
                'images' => '["https://escortsmassage.com/images/users/6.webp"]',
                'main_image' => 'https://escortsmassage.com/images/users/6.webp',
                'intercourse_options' => '["GV", "Franz.", "Franz. bei Ihr", "Franz. beidseitig", "Span. / BV"]',
                'services_for' => '["Herren"]',
                'services' => '["DS passiv", "Mast.", "Badeservice", "Duschservice", "gekonnter Striptease"]',
                'meetings' => '["mit Termin", "ohne Termin"]',
                'massages' => '["erot. Massagen", "Body-to-Body-Massage", "Fetisch / Softbizarr", "Fetisch-Spielchen"]',
                'schedule' => 'Montag: 10:00 - 21:30 Uhr (n. Abspr.)\nDienstag: 10:00 - 21:30 Uhr (n. Abspr.)\nMittwoch: 10:00 - 21:30 Uhr (n. Abspr.)\nDonnerstag: 10:00 - 21:30 Uhr (n. Abspr.)\nFreitag: 10:00 - 21:30 Uhr (n. Abspr.)\nSamstag: 10:00 - 21:30 Uhr (n. Abspr.)\nSonntag: 12:00 - 21:30 Uhr (n. Abspr.)\nFeiertag: 12:00 - 21:30 Uhr (n. Abspr.)',
                'additional_info' => null,
                'profile_options' => null,
                'created_at' => '2025-08-28 15:15:26',
                'updated_at' => '2025-09-24 20:59:19',
            ],
            [
                'id' => 19,
                'name' => 'Sara',
                'age' => 25,
                'gender' => 'weiblich',
                'height' => 161,
                'bust_size' => '75 D, natur',
                'body_type' => 'südländisch',
                'origin' => 'Italien',
                'clothing_size' => '38',
                'weight' => 60,
                'shoe_size' => 36,
                'intimate_area' => 'total rasiert',
                'hair' => 'dunkelblond, schulterlang',
                'eyes' => 'braun',
                'skin' => 'hell',
                'body_jewelry' => 'kein Körperschmuck',
                'languages' => '["Englisch", "Spanisch", "Italienisch"]',
                'other' => 'Nichtraucher',
                'description' => null,
                'image' => 'https://escortsmassage.com/images/users/7.webp',
                'images' => '["https://escortsmassage.com/images/users/7.webp"]',
                'main_image' => 'https://escortsmassage.com/images/users/7.webp',
                'intercourse_options' => '["GV", "Franz. bei Ihr", "Franz. beidseitig", "Span. / BV"]',
                'services_for' => '["Herren"]',
                'services' => '["Schmusen, Kuscheln", "DS passiv", "ZA passiv", "FA / An*l-Massagen passiv", "GB passiv", "KB passiv", "Fingerspiele passiv", "Badeservice", "Duschservice", "Fuß- / Schuherotik", "Verbalerotik"]',
                'meetings' => null,
                'massages' => '["erot. Massagen", "HE", "Body-to-Body-Massage", "Thai-Massage", "Ganzkörper-Massage", "Öl-Massage", "Synchron-Massage", "Nuru-Massage", "Pr*stata-Massage", "Lingam-Massage"]',
                'schedule' => 'Montag: 10:00 - 21:30 Uhr (n. Abspr.)\nDienstag: 10:00 - 21:30 Uhr (n. Abspr.)\nMittwoch: 10:00 - 21:30 Uhr (n. Abspr.)\nDonnerstag: 10:00 - 21:30 Uhr (n. Abspr.)\nFreitag: 10:00 - 21:30 Uhr (n. Abspr.)\nSamstag: 10:00 - 21:30 Uhr (n. Abspr.)\nSonntag: 12:00 - 21:30 Uhr (n. Abspr.)\nFeiertag: 12:00 - 21:30 Uhr (n. Abspr.)',
                'additional_info' => null,
                'profile_options' => null,
                'created_at' => '2025-08-28 15:15:26',
                'updated_at' => '2025-09-24 20:59:19',
            ],
            [
                'id' => 20,
                'name' => 'Alina',
                'age' => 25,
                'gender' => 'weiblich',
                'height' => 165,
                'bust_size' => '75 B, natur',
                'body_type' => 'westeuropäisch',
                'origin' => 'Rumänien',
                'clothing_size' => '36',
                'weight' => 50,
                'shoe_size' => 37,
                'intimate_area' => 'total rasiert',
                'hair' => 'blond, rückenlang, glatt',
                'eyes' => 'grün',
                'skin' => 'hell',
                'body_jewelry' => 'Tattoos',
                'languages' => '["Deutsch", "Englisch", "Spanisch", "Rumänisch"]',
                'other' => null,
                'description' => null,
                'image' => 'https://escortsmassage.com/images/users/8.webp',
                'images' => '["https://escortsmassage.com/images/users/8.webp"]',
                'main_image' => 'https://escortsmassage.com/images/users/8.webp',
                'intercourse_options' => '["GV", "Franz.", "Franz. bei Ihr", "Franz. beidseitig", "Span. / BV"]',
                'services_for' => '["Herren"]',
                'services' => '["Schmusen, Kuscheln", "Körperküsse", "AV bei Ihm", "ZA passiv", "FA / An*l-Massagen aktiv", "FA / An*l-Massagen passiv", "KB passiv", "Fingerspiele aktiv", "Fingerspiele passiv", "Duschservice", "extra langes Vorspiel", "Fuß- / Schuherotik", "Intimrasur", "Nylonerotik"]',
                'meetings' => null,
                'massages' => '["erot. Massagen", "HE", "Body-to-Body-Massage", "Ganzkörper-Massage", "Intim-Massagen", "Öl-Massage", "Pr*stata-Massage", "Po-Massage", "Fetisch / Softbizarr", "Dom. Biz.-Spielchen", "Fetisch-Spielchen", "Lack u. Leder", "Latex", "FS", "leichte Erz.", "Fess.-Spielchen passiv", "Bru*tw.-Spiele passiv"]',
                'schedule' => 'Montag: 10:00 - 21:30 Uhr (n. Abspr.)\nDienstag: 10:00 - 21:30 Uhr (n. Abspr.)\nMittwoch: 10:00 - 21:30 Uhr (n. Abspr.)\nDonnerstag: 10:00 - 21:30 Uhr (n. Abspr.)\nFreitag: 10:00 - 21:30 Uhr (n. Abspr.)\nSamstag: 10:00 - 21:30 Uhr (n. Abspr.)\nSonntag: 12:00 - 21:30 Uhr (n. Abspr.)\nFeiertag: 12:00 - 21:30 Uhr (n. Abspr.)',
                'additional_info' => null,
                'profile_options' => null,
                'created_at' => '2025-08-28 15:15:26',
                'updated_at' => '2025-09-24 20:59:19',
            ],
            [
                'id' => 21,
                'name' => 'Chloe',
                'age' => 23,
                'gender' => 'weiblich',
                'height' => 165,
                'bust_size' => '75 B',
                'body_type' => 'osteuropäisch',
                'origin' => 'Osteuropa',
                'clothing_size' => '34',
                'weight' => null,
                'shoe_size' => null,
                'intimate_area' => 'total rasiert',
                'hair' => 'dunkelbraun, rückenlang, glatt',
                'eyes' => 'braun',
                'skin' => 'mittel',
                'body_jewelry' => null,
                'languages' => '["Deutsch", "Englisch"]',
                'other' => null,
                'description' => null,
                'image' => 'https://escortsmassage.com/images/users/9.webp',
                'images' => '["https://escortsmassage.com/images/users/9.webp"]',
                'main_image' => 'https://escortsmassage.com/images/users/9.webp',
                'intercourse_options' => '["GV", "Franz.", "Franz. bei Ihr", "Franz. beidseitig", "Span. / BV", "GF6"]',
                'services_for' => '["Herren"]',
                'services' => '["ZK", "Schmusen, Kuscheln", "Körperküsse", "DS aktiv", "DS passiv", "KB passiv", "Fingerspiele aktiv", "Fingerspiele passiv", "EL", "Mast.", "Badeservice", "Duschservice", "extra langes Vorspiel", "gekonnter Striptease", "Fuß- / Schuherotik"]',
                'meetings' => null,
                'massages' => '["erot. Massagen", "HE", "Body-to-Body-Massage", "Ganzkörper-Massage", "Intim-Massagen"]',
                'schedule' => 'Montag: 10:00 - 21:30 Uhr (n. Abspr.)\nDienstag: 10:00 - 21:30 Uhr (n. Abspr.)\nMittwoch: 10:00 - 21:30 Uhr (n. Abspr.)\nDonnerstag: 10:00 - 21:30 Uhr (n. Abspr.)\nFreitag: 10:00 - 21:30 Uhr (n. Abspr.)\nSamstag: 10:00 - 21:30 Uhr (n. Abspr.)\nSonntag: 12:00 - 21:30 Uhr (n. Abspr.)\nFeiertag: 12:00 - 21:30 Uhr (n. Abspr.)',
                'additional_info' => null,
                'profile_options' => null,
                'created_at' => '2025-08-28 15:15:26',
                'updated_at' => '2025-09-24 20:59:19',
            ],
            [
                'id' => 22,
                'name' => 'Stefanie',
                'age' => 33,
                'gender' => 'weiblich',
                'height' => 159,
                'bust_size' => '80 D',
                'body_type' => 'Latina',
                'origin' => null,
                'clothing_size' => '38',
                'weight' => 70,
                'shoe_size' => 37,
                'intimate_area' => 'total rasiert',
                'hair' => 'brünett, rückenlang',
                'eyes' => 'braun',
                'skin' => 'mittel',
                'body_jewelry' => 'Brustwarzen-Piercing, Tattoos',
                'languages' => '["Englisch", "Spanisch"]',
                'other' => 'Nichtraucher',
                'description' => null,
                'image' => 'https://escortsmassage.com/images/users/10.webp',
                'images' => '["https://escortsmassage.com/images/users/10.webp"]',
                'main_image' => 'https://escortsmassage.com/images/users/10.webp',
                'intercourse_options' => '["AV", "GV", "Franz.", "Franz. beidseitig", "D**p Thr**t", "Span. / BV"]',
                'services_for' => '["Herren"]',
                'services' => '["ZK", "Körperküsse", "AV bei Ihm", "DS passiv", "ZA passiv", "FA / An*l-Massagen aktiv", "KB passiv", "Fingerspiele passiv", "EL", "Mast.", "LS / Duo", "Badeservice", "Duschservice", "extra langes Vorspiel", "Intimrasur", "Nylonerotik"]',
                'meetings' => null,
                'massages' => '["erot. Massagen", "HE", "Body-to-Body-Massage", "Tantra-Massage", "Intim-Massagen", "Öl-Massage", "Synchron-Massage", "Duo-Massage", "Nuru-Massage", "Pr*stata-Massage", "Po-Massage", "Lingam-Massage", "Fetisch / Softbizarr", "Dom. Biz.-Spielchen", "NS aktiv", "Bru*tw.-Spiele aktiv"]',
                'schedule' => 'Montag: 10:00 - 21:30 Uhr (n. Abspr.)\nDienstag: 10:00 - 21:30 Uhr (n. Abspr.)\nMittwoch: 10:00 - 21:30 Uhr (n. Abspr.)\nDonnerstag: 10:00 - 21:30 Uhr (n. Abspr.)\nFreitag: 10:00 - 21:30 Uhr (n. Abspr.)\nSamstag: 10:00 - 21:30 Uhr (n. Abspr.)\nSonntag: 12:00 - 21:30 Uhr (n. Abspr.)\nFeiertag: 12:00 - 21:30 Uhr (n. Abspr.)',
                'additional_info' => null,
                'profile_options' => null,
                'created_at' => '2025-08-28 15:15:26',
                'updated_at' => '2025-09-24 20:59:19',
            ],
        ];

        foreach ($profiles as $profileData) {
            Profile::updateOrCreate(
                ['id' => $profileData['id']],
                $profileData
            );
        }
    }
}
