<?php
return array (
  0 => 
  array (
    'id' => '1',
    'name' => 'Michael K.',
    'date' => '2025-01-15',
    'rating' => '5',
    'service' => 'VIP Service',
    'message' => 'Absolut fantastische Erfahrung! Maya war unglaublich professionell und einfühlsam. Die VIP Suite ist luxuriös und die Atmosphäre perfekt. Werde definitiv wiederkommen!',
    'verified' => '1',
    'created_at' => '2025-08-27 19:12:35',
    'updated_at' => '2025-08-27 19:12:35',
  ),
  1 => 


  
  array (
    'id' => '2',
    'name' => 'Stefan W.',
    'date' => '2025-01-12',
    'rating' => '5',
    'service' => 'Tantra Massage',
    'message' => 'Kira hat mir eine spirituelle Erfahrung bereitet, die ich nie vergessen werde. Die Tantra Massage war transformativ und heilend. Höchste Empfehlung!',
    'verified' => '1',
    'created_at' => '2025-08-27 19:12:35',
    'updated_at' => '2025-08-27 19:12:35',
  ),
  2 => 
  array (
    'id' => '3',
    'name' => 'Alexander M.',
    'date' => '2025-01-08',
    'rating' => '5',
    'service' => 'Paar Erlebnis',
    'message' => 'Meine Partnerin und ich hatten ein wunderbares Erlebnis. Lila und Nira haben uns beide verwöhnt und eine romantische Atmosphäre geschaffen. Perfekt für Paare!',
    'verified' => '1',
    'created_at' => '2025-08-27 19:12:35',
    'updated_at' => '2025-08-27 19:12:35',
  ),
  3 => 
  array (
    'id' => '4',
    'name' => 'Thomas B.',
    'date' => '2025-01-05',
    'rating' => '4',
    'service' => 'Erotik Massage',
    'message' => 'Sehr professioneller Service und diskrete Atmosphäre. Ploy war charmant und aufmerksam. Einziger Punkt: Parkplätze sind etwas knapp, aber das Studio ist es wert.',
    'verified' => '1',
    'created_at' => '2025-08-27 19:12:35',
    'updated_at' => '2025-08-27 19:12:35',
  ),
  4 => 
  array (
    'id' => '5',
    'name' => 'Robert H.',
    'date' => '2025-01-02',
    'rating' => '5',
    'service' => 'Body-to-Body',
    'message' => 'Siri ist eine Künstlerin! Die Body-to-Body Massage war intensiv und entspannend zugleich. Die Räumlichkeiten sind sehr sauber und elegant eingerichtet.',
    'verified' => '1',
    'created_at' => '2025-08-27 19:12:35',
    'updated_at' => '2025-08-27 19:12:35',
  ),
  5 => 
  array (
    'id' => '6',
    'name' => 'Daniel L.',
    'date' => '2024-12-28',
    'rating' => '5',
    'service' => 'Girlfriend Experience',
    'message' => 'Maya hat mir einen unvergesslichen Abend bereitet. Das Girlfriend Experience war authentisch und liebevoll. Fühlt sich an wie ein echtes Date. Absolut empfehlenswert!',
    'verified' => '1',
    'created_at' => '2025-08-27 19:12:35',
    'updated_at' => '2025-08-27 19:12:35',
  ),
  6 => 
  array (
    'id' => '7',
    'name' => 'Test User',
    'date' => '2025-08-28',
    'rating' => '5',
    'service' => 'Test Service',
    'message' => 'Test message',
    'verified' => '0',
    'created_at' => '2025-08-27 19:42:31',
    'updated_at' => '2025-08-27 19:42:31',
  ),
  7 => 
  array (
    'id' => '8',
    'name' => 'aaaa',
    'date' => '2025-08-27',
    'rating' => '5',
    'service' => 'Tantra Massage',
    'message' => 'dfghshydhfs',
    'verified' => '0',
    'created_at' => '2025-08-27 19:44:11',
    'updated_at' => '2025-08-27 19:44:11',
  ),
  8 => 
  array (
    'id' => '9',
    'name' => 'irtirtitritrirti',
    'date' => '2025-08-27',
    'rating' => '5',
    'service' => 'Tantra Massage',
    'message' => 'tyitryi',
    'verified' => '1',
    'created_at' => '2025-08-27 20:00:14',
    'updated_at' => '2025-08-27 20:00:33',
  ),
  9 => 
  array (
    'id' => '10',
    'name' => 'Michael K.',
    'date' => '2025-01-15',
    'rating' => '5',
    'service' => 'VIP Service',
    'message' => 'Absolut fantastische Erfahrung! Maya war unglaublich professionell und einfühlsam. Die VIP Suite ist luxuriös und die Atmosphäre perfekt. Werde definitiv wiederkommen!',
    'verified' => '1',
    'created_at' => '2025-09-25 00:25:52',
    'updated_at' => '2025-09-25 00:25:52',
  ),
  10 => 
  array (
    'id' => '11',
    'name' => 'Stefan W.',
    'date' => '2025-01-12',
    'rating' => '5',
    'service' => 'Tantra Massage',
    'message' => 'Kira hat mir eine spirituelle Erfahrung bereitet, die ich nie vergessen werde. Die Tantra Massage war transformativ und heilend. Höchste Empfehlung!',
    'verified' => '1',
    'created_at' => '2025-09-25 00:25:52',
    'updated_at' => '2025-09-25 00:25:52',
  ),
  11 => 
  array (
    'id' => '12',
    'name' => 'Alexander M.',
    'date' => '2025-01-08',
    'rating' => '5',
    'service' => 'Paar Erlebnis',
    'message' => 'Meine Partnerin und ich hatten ein wunderbares Erlebnis. Lila und Nira haben uns beide verwöhnt und eine romantische Atmosphäre geschaffen. Perfekt für Paare!',
    'verified' => '1',
    'created_at' => '2025-09-25 00:25:52',
    'updated_at' => '2025-09-25 00:25:52',
  ),
  12 => 
  array (
    'id' => '13',
    'name' => 'Thomas B.',
    'date' => '2025-01-05',
    'rating' => '4',
    'service' => 'Erotik Massage',
    'message' => 'Sehr professioneller Service und diskrete Atmosphäre. Ploy war charmant und aufmerksam. Einziger Punkt: Parkplätze sind etwas knapp, aber das Studio ist es wert.',
    'verified' => '1',
    'created_at' => '2025-09-25 00:25:52',
    'updated_at' => '2025-09-25 00:25:52',
  ),
  13 => 
  array (
    'id' => '14',
    'name' => 'Robert H.',
    'date' => '2025-01-02',
    'rating' => '5',
    'service' => 'Body-to-Body',
    'message' => 'Siri ist eine Künstlerin! Die Body-to-Body Massage war intensiv und entspannend zugleich. Die Räumlichkeiten sind sehr sauber und elegant eingerichtet.',
    'verified' => '1',
    'created_at' => '2025-09-25 00:25:53',
    'updated_at' => '2025-09-25 00:25:53',
  ),
  14 => 
  array (
    'id' => '15',
    'name' => 'Daniel L.',
    'date' => '2024-12-28',
    'rating' => '5',
    'service' => 'Girlfriend Experience',
    'message' => 'Maya hat mir einen unvergesslichen Abend bereitet. Das Girlfriend Experience war authentisch und liebevoll. Fühlt sich an wie ein echtes Date. Absolut empfehlenswert!',
    'verified' => '1',
    'created_at' => '2025-09-25 00:25:53',
    'updated_at' => '2025-09-25 00:25:53',
  ),
);
